from enum import Enum
class TermSymb(Enum):
    ID = 'ident'
    IDFUNC = 'ident_func'
    LPAREN = '('
    RPAREN = ')'
    NULLCONST = 'null'
    STRINGCONST = 'string_constant'
    FLOATCONST = 'float_constant'
    INTCONST = 'int_constant'
    REM = '%'
    SLASH = '/'
    STAR = '*'
    MINUS = '-'
    PLUS = '+'
    NEQ = '!='
    EQ = '=='
    GE = '>='
    LE = '<='
    GT = '>'
    LT = '<'
    SEMICOLON = ';'
    COMMA = ','
    DOT = '.'
    ASSIGN = '='
    LBRACKET = '['
    RBRACKET = ']'
    LBRACE = '{'
    RBRACE = '}'
    DEF = 'def'
    NEW = 'new'
    BREAK = 'break'
    FOR = 'for'
    IF = 'if'
    ELSE = 'else'
    INT = 'int'
    FLOAT = 'float'
    STRING = 'string'
    PRINT = 'print'
    READ = 'read'
    RETURN = 'return'

    # Don't belong to the language
    ENDSTACK = '$'
    EPSILON = 'ε'
